### ISSUE TITLE
It is not working!

### ISSUE THREAD

**Issue by andre-filho** [andre-filho/commit-helper#86]
**Describe the bug**
It is breaking AF

**To Reproduce**
 $ commit -ca 'gui <guilherme.francais@gmail.com>'
You are using the changelog convention
type the tag: add
type the commit message: apex and dependencies
Traceback (most recent call last):
  File "/home/andre/.local/bin/commit", line 10, in <module>
    sys.exit(main())
  File "/home/andre/.local/lib/python3.5/site-packages/commit_helper/__main__.py", line 32, in main
    handle_file_based_commit(file_path, debug_mode, args)
  File "/home/andre/.local/lib/python3.5/site-packages/commit_helper/utils/file_handler.py", line 39, in handle_file_based_commit
    commit_msg = handle_conventioned_commit(convention, args)
  File "/home/andre/.local/lib/python3.5/site-packages/commit_helper/utils/utils.py", line 108, in handle_conventioned_commit
    return commit_message
UnboundLocalError: local variable 'commit_message' referenced before assignment

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andre-filho** [comment]
fixed
